### ISSUE TITLE
NullPointerException when using Purpur 1.18.1

### ISSUE THREAD

**Issue by Dreamail** [Apisium/PaperShelled#1]
paichen@chens-Mac-mini PluginDevEnv % java -javaagent:PaperShelled-0.0.1.jar -jar purpur-paperclip-1.18.1-R0.1-SNAPSHOT-reobf.jar --nogui
[14:18:59 INFO]: [PaperShelled] PaperShelled version: 0.0.1 (Thu, Sep 16, 2021 05:57:56 AM GMT)
[14:18:59 INFO]: [PaperShelled] You can get the latest updates from: https://github.com/Apisium/PaperShelled
[14:18:59 INFO]: [PaperShelled:mixin] SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Volumes/PiExDisk/Code/Minecraft/Server/PluginDevEnv/PaperShelled-0.0.1.jar Service=PaperShelled Env=SERVER
[14:18:59 INFO]: [PaperShelled:mixin] Attempting to load Hot-Swap agent
Starting org.bukkit.craftbukkit.Main
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at cn.apisium.papershelled.PaperShelledAgent$Transformer.transform(PaperShelledAgent.java:45)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:38)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "ServerMain" java.lang.NoClassDefFoundError: cn/apisium/papershelled/PaperShelledAgent
	at org.bukkit.craftbukkit.Main.main(Unknown Source)
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: cn.apisium.papershelled.PaperShelledAgent
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more
paichen@chens-Mac-mini PluginDevEnv %

**Comment by ShirasawaSama** [comment]
1.18.1不能正常使用是已知问题，等待 @InitAuther97 进行修复

**Comment by Dreamail** [comment]
https://github.com/PaperMC/Paperclip/pull/49#issuecomment-999937732
Here is some useful pr.

**Comment by Dreamail** [comment]
I will try to fix it.

**Comment by ShirasawaSama** [comment]
> I will try to fix it.

Ok, thanks for your PR.

**Comment by InitAuther97** [comment]
I think I've found a way that didn't launch the server through Paperclip but to launch the server directly. This actually fix the problem (successfully launched the purpur-1.18.1-1551 and paper-1.18.1-187 with a PaperShelled plugin of my own), but this changed how PaperShelled is used and it's a bit different from a general server jar, probably more like a launcher.I'll test it further for its stability.

**Comment by InitAuther97** [comment]
Detailed information can be seen here.
[https://github.com/InitAuther97/PaperShelled](url)

**Comment by ShirasawaSama** [comment]
#2

**Comment by Dreamail** [comment]
maybe we can modify paperclip directly, using asm and javaagent.

**Comment by Dreamail** [comment]
But now I am being trapped in compiling a papershelled plugin.

**Comment by InitAuther97** [comment]
> maybe we can modify paperclip directly, using asm and javaagent.

Yeah I think so, but I always encounter problems after modifying it with ASM. Sure I have no idea how to modify those StackMap or something XD

**Comment by Dreamail** [comment]
> > maybe we can modify paperclip directly, using asm and javaagent.
> 
> Yeah I think so, but I always encounter problems after modifying it with ASM. Sure I have no idea how to modify those StackMap or something XD

Maybe just replace the class?

**Comment by InitAuther97** [comment]
> > > maybe we can modify paperclip directly, using asm and javaagent.
> > 
> > 
> > Yeah I think so, but I always encounter problems after modifying it with ASM. Sure I have no idea how to modify those StackMap or something XD
> 
> Maybe just replace the class?

Actually I thought about it. I think it's not such a good way to solve it.
Now I made it to replace the main(String[]) with my own using ASM, thanks to an ASM bytecode viewer plugin
It is good that in this way we don't change the way PaperShelled is used.

**Comment by Dreamail** [comment]
I'm wondering how to compile a papershelled plugin.
